### ISSUE TITLE
set_background_color error on windows machine

### ISSUE THREAD

**Issue by mirbagheri** [LABSN/expyfun#286]
Running any function from visuals (set_background_color, FixationDot, etc) on windows results in the following error:

```
Traceback (most recent call last):
  File "C:\Experiments\mbagheri\aud_att_int_SAMPLE\aud_att_int.py", line 35, in <module>
    ec.set_background_color([0.2] * 3)
  File "C:\Experiments\mbagheri\aud_att_int_SAMPLE\expyfun\_experiment_controller.py", line 540, in set_background_color
    Rectangle(self, pos=[0, 0, 2.1, 2.1], fill_color=color).draw()
  File "C:\Experiments\mbagheri\aud_att_int_SAMPLE\expyfun\visual\_visual.py", line 476, in __init__
    line_loop=True)
  File "C:\Experiments\mbagheri\aud_att_int_SAMPLE\expyfun\visual\_visual.py", line 191, in __init__
    _check_log(vertex, gl.glGetShaderInfoLog)
  File "C:\Experiments\mbagheri\aud_att_int_SAMPLE\expyfun\visual\_visual.py", line 172, in _check_log
    raise RuntimeError(message)
RuntimeError: No errors.
``` 
Updating pyglet didn't help. Any ideas?

**Comment by Eric89GXL** [comment]
Can you try downgrading pyglet? @drammock ran tests a few days ago on
windows and they passed, so I suspect there is a regression in a dependency

**Comment by drammock** [comment]
@Eric89GXL FYI this is happening on the laptop we use for task practice during MEG capping.  I'm suspecting an expyfun issue, not a pyglet one.  One notable irregularity was that the machine had no expyfun config file set up.  I'm trying now to see if I can reproduce on windows on my laptop.

**Comment by drammock** [comment]
reproduced on my laptop:

```python
from expyfun import ExperimentController

kwargs = dict(exp_name='test', session='test', participant='test',
              output_dir=None, version='796be20')

with ExperimentController(**kwargs) as ec:
    ec.set_background_color([0.2] * 3)
    ec.wait_secs(1.5)
```
```
2016-07-26 01:29:22,040 - INFO    - Expyfun: Setting up Pyglet audio
2016-07-26 01:29:22,118 - INFO    - Expyfun: Setting up screen
2016-07-26 01:29:22,338 - EXP     - Expyfun: Set screen visibility True
2016-07-26 01:29:22,509 - INFO    - Expyfun: Initializing dummy triggering mode
2016-07-26 01:29:22,525 - INFO    - Expyfun: Initialization complete
2016-07-26 01:29:22,525 - EXP     - Expyfun: Subject: test
2016-07-26 01:29:22,525 - EXP     - Expyfun: Session: test
2016-07-26 01:29:22,650 - EXP     - Expyfun: Audio stopped and reset.
Traceback (most recent call last):
  File "D:\Desktop\test\test.py", line 9, in <module>
    ec.set_background_color([0.2] * 3)
  File "D:\Desktop\test\expyfun\_experiment_controller.py", line 540, in set_background_color
    Rectangle(self, pos=[0, 0, 2.1, 2.1], fill_color=color).draw()
  File "D:\Desktop\test\expyfun\visual\_visual.py", line 476, in __init__
    line_loop=True)
  File "D:\Desktop\test\expyfun\visual\_visual.py", line 191, in __init__
    _check_log(vertex, gl.glGetShaderInfoLog)
  File "D:\Desktop\test\expyfun\visual\_visual.py", line 172, in _check_log
    raise RuntimeError(message)
RuntimeError: No errors.
```

**Comment by drammock** [comment]
Not positive, but it looks like the `_get_log` function [here](https://github.com/LABSN/expyfun/blob/master/expyfun/visual/_visual.py#L166-L172) is expected to return `None` (or an empty string?) when there are no errors, but on my laptop and the training laptop, it is returning 'no errors'.  Creating PR now...

**Comment by Eric89GXL** [comment]
That machine doesn't need a configuration file, the defaults should be
fine.

We never had that problem before, I wonder why it's happening now. Didn't
happen on Marlo, right?

In any case, I agree it should be fine to check for the no error message
