### ISSUE TITLE
identify_trial error

### ISSUE THREAD

**Issue by mfreilly** [LABSN/expyfun#335]
expyfun does display grayscale images. Now when I loop through an image list I get:

Traceback (most recent call last):
  File "/Volumes/TimeMachineBackups/MEG_Data/expyfun_MEG_experiments/DevZ/DevZ.py", line 63, in <module>
    ec.identify_trial(ec_id='MFR', ttl_id=[0])
  File "/Users/mreilly2/anaconda/lib/python2.7/site-packages/expyfun-2.0.0.dev0+b796f5f-py2.7.egg/expyfun/_experiment_controller.py", line 1715, in identify_trial
    raise RuntimeError('Cannot identify a trial twice')
RuntimeError: Cannot identify a trial twice

**Comment by larsoner** [comment]
The cycle is supposed to be `identify_trial` -> `start_stimulus` -> `trial_ok`, you are probably doing two `identify_trial` calls in a row which is not allowed (there should be a single one per trial)

**Comment by mfreilly** [comment]
That's it, thanks.
